<Project Sdk="Microsoft.NET.Sdk">

   

  <ItemGroup>
    <None Include="Features\Users\Commands\Models\RegisterUserDto.cs" />
  </ItemGroup>

   

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

   

  <ItemGroup>
    <ProjectReference Include="..\InfraStructure\InfraStructure.csproj" />
  </ItemGroup>

</Project>
